//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.20 at 02:54:09 PM CEST 
//


package com.example.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSportEventsByNameResponse }
     * 
     */
    public GetSportEventsByNameResponse createGetSportEventsByNameResponse() {
        return new GetSportEventsByNameResponse();
    }

    /**
     * Create an instance of {@link SportEvents }
     * 
     */
    public SportEvents createSportEvents() {
        return new SportEvents();
    }

    /**
     * Create an instance of {@link AddSportEventResponse }
     * 
     */
    public AddSportEventResponse createAddSportEventResponse() {
        return new AddSportEventResponse();
    }

    /**
     * Create an instance of {@link GetByLocationResponse }
     * 
     */
    public GetByLocationResponse createGetByLocationResponse() {
        return new GetByLocationResponse();
    }

    /**
     * Create an instance of {@link RemoveSportEventByIdRequest }
     * 
     */
    public RemoveSportEventByIdRequest createRemoveSportEventByIdRequest() {
        return new RemoveSportEventByIdRequest();
    }

    /**
     * Create an instance of {@link GetSportEventsByStatusRequest }
     * 
     */
    public GetSportEventsByStatusRequest createGetSportEventsByStatusRequest() {
        return new GetSportEventsByStatusRequest();
    }

    /**
     * Create an instance of {@link GetByLocationRequest }
     * 
     */
    public GetByLocationRequest createGetByLocationRequest() {
        return new GetByLocationRequest();
    }

    /**
     * Create an instance of {@link GetSportEventsByNameRequest }
     * 
     */
    public GetSportEventsByNameRequest createGetSportEventsByNameRequest() {
        return new GetSportEventsByNameRequest();
    }

    /**
     * Create an instance of {@link RemoveSportEventByIdResponse }
     * 
     */
    public RemoveSportEventByIdResponse createRemoveSportEventByIdResponse() {
        return new RemoveSportEventByIdResponse();
    }

    /**
     * Create an instance of {@link GetAllSportEventsRequest }
     * 
     */
    public GetAllSportEventsRequest createGetAllSportEventsRequest() {
        return new GetAllSportEventsRequest();
    }

    /**
     * Create an instance of {@link AddSportEventRequest }
     * 
     */
    public AddSportEventRequest createAddSportEventRequest() {
        return new AddSportEventRequest();
    }

    /**
     * Create an instance of {@link SportEventDTO }
     * 
     */
    public SportEventDTO createSportEventDTO() {
        return new SportEventDTO();
    }

    /**
     * Create an instance of {@link GetAllSportEventsResponse }
     * 
     */
    public GetAllSportEventsResponse createGetAllSportEventsResponse() {
        return new GetAllSportEventsResponse();
    }

    /**
     * Create an instance of {@link GetSportEventsByStatusResponse }
     * 
     */
    public GetSportEventsByStatusResponse createGetSportEventsByStatusResponse() {
        return new GetSportEventsByStatusResponse();
    }

    /**
     * Create an instance of {@link SportEvent }
     * 
     */
    public SportEvent createSportEvent() {
        return new SportEvent();
    }

}
